name: tower-action
author: Phil Ewels

description: Launch a workflow using Nextflow Tower (https://tower.nf)

branding:
  icon: 'play'
  color: 'purple'

inputs:
  access_token:
    description: Nextflow Tower access token
    required: true
  compute_env:
    description: Nextflow Tower compute env
    required: false
  workspace_id:
    description: Nextflow Tower workspace ID
    required: false
  api_endpoint:
    description: Tower API URL
    required: false
    default: https://api.tower.nf
  pipeline:
    description: Pipeline repository
    default: ${{ github.repository }}
    required: false
  revision:
    description: Pipeline revision (release / branch)
    default: ${{ github.sha }}
    required: false
  workdir:
    description: Nextflow work directory
    required: true
  parameters:
    description: Pipeline parameters
    required: false
  profiles:
    description: Nextflow config profiles
    required: false
  nextflow_config:
    description: Nextflow config options
    required: false
  pre_run_script:
    description: Pre-run script before launch
    required: false

runs:
  using: 'docker'
  image: Dockerfile
  env:
    TOWER_WORKSPACE_ID: ${{ inputs.workspace_id }}
    TOWER_API_ENDPOINT: ${{ inputs.api_endpoint }}
    TOWER_ACCESS_TOKEN: ${{ inputs.access_token }}
    TOWER_COMPUTE_ENV: ${{ inputs.compute_env }}
    PIPELINE: ${{ inputs.pipeline }}
    REVISION: ${{ inputs.revision }}
    WORKDIR: ${{ inputs.workdir }}
    PARAMETERS: ${{ toJson(fromJson(inputs.parameters)) }}
    CONFIG_PROFILES: ${{ inputs.profiles }}
    NEXTFLOW_CONFIG: ${{ inputs.nextflow_config }}
    PRE_RUN_SCRIPT: ${{ inputs.pre_run_script }}
